# [START gcloud build gradle]
steps:
  - name: gradle:6.8.2-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:6.8.2-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/demo-gcp-1", "--build-arg=JAR_FILE=build/libs/demo-gcp-1-0.0.1.jar", "."]
images: ["gcr.io/$PROJECT_ID/demo-gcp-1"]
# [END gcloud build gradle]
